### ISSUE TITLE
Going sad while in ghost causes a crash

### ISSUE THREAD

**Issue by hypsin88** [Toontown-Offline-Issue-Tracker/issues#47]
```python
Traceback (most recent call last):
  File "direct.showbase.ShowBase", line 3185, in run
  File "direct.task.Task", line 561, in run
  File "direct.task.Task", line 489, in step
  File "direct.showbase.PythonUtil", line 1861, in _doCallback
  File "toontown.hood.Place", line 121, in _doSetZoneCompleteLocalCallbacks
  File "otp.otpbase.PythonUtil", line 4292, in __call__
  File "direct.showbase.PythonUtil", line 82, in _do__call__
  File "toontown.hood.Place", line 684, in _placeTeleportInPostZoneComplete
  File "otp.avatar.LocalAvatar", line 1264, in d_broadcastPositionNow
TypeError: 'NoneType' object is not callable
```

Do note this was during a stinkfest.

**Comment by Benjamin8693** [comment]
Duplicate issue.
